#!/bin/bash
git clone https://github.com/bwilk7/lupyter.git
cd lupyter
python setup.py install
jupyter kernelspec install ../lupyter --user
luarocks install inspect --local
python ~/binder/set_envs.py ~/.local/share/jupyter/kernels/lupyter/kernel.json ~/binder/lua_env 

wget http://ftp.gnu.org/gnu/mit-scheme/stable.pkg/9.2/mit-scheme-9.2-x86-64.tar.gz
tar xvf mit-scheme-9.2-x86-64.tar.gz
cd mit-scheme-9.2/src/
./configure
make compile-microcode
make install
