#!/bin/bash
git clone https://github.com/bwilk7/lupyter.git
cd lupyter
python setup.py install
jupyter kernelspec install ../lupyter --user
luarocks install inspect --local
python ~/binder/set_envs.py ~/.local/share/jupyter/kernels/lupyter/kernel.json ~/binder/lua_env 

